
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/gvimrc_example.vim

"runtimepath
set rtp+=~/.vim/mine

"use forward slashes in file names;
set ssl

set autochdir
"Auto change to editing file's cwd
autocmd BufEnter * cd %:p:h

"不使用备份文件
set nobackup
"不生成swap文件，当buffuer被丢弃时隐藏它
set noswapfile
set bufhidden=hide

set guioptions-=b
set guioptions-=r
set guioptions-=l
"set guioptions-=m   "隐藏菜单
set guioptions-=T   "隐藏工具栏
set guioptions=m

"设置窗口大小和初始位置
set lines=35
set columns=120
winpos 400 100
"设置命令行的高度
set cmdheight=1

"载入文件类型插件
filetype plugin on
"为特定类型文件载入缩进文件
filetype indent on

highlight StatusLine guifg=SlateBlue guibg=Yellow
highlight StatusLineNC guifg=Gray guibg=White

"自动格式化
set formatoptions=tcrqn
"继承前一行的缩进方式自动缩进
set autoindent
"使用c风格的缩进
set cindent
"为c程序提供自动缩进
set smartindent

"不自动换行
set nowrap
autocmd BufRead,BufNewFile *.txt set wrap
autocmd BufRead,BufNewFile *.note set wrap

" txtBrowser
au BufEnter *.txt setlocal ft=txt

"让特俗词汇不做标点符号处理（不换行）
set iskeyword+=_,$,@,%,#,-

"首行缩进1个tab
set smarttab

"tab为4个空格长
set tabstop=4
"统一缩进为4个空格长
set softtabstop=4
set shiftwidth=4
"tab转换为空格
set expandtab

"语法高亮
syntax on

"行距，单位为像素
set linespace=1

"显示行号
set number

"高亮显示匹配的括号
set showmatch
"匹配括号高亮的时间，单位为1/10s
set matchtime=5
"搜索时忽略大小写
set ignorecase
"不高亮被搜索的句子
set nohlsearch

"当光标距离窗口顶、底部8行时自动向下移动
set scrolloff=5

"不使用vi键盘模式，使用vim模式
set nocompatible

"高亮当前行
"set cursorline

"高亮搜索
set hlsearch

"显示输入的命令
set showcmd

"设定文字编码
"set encoding=utf-8
set fenc=utf-8
set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936

"在处理未保存或只读文件时，弹出确认框
set confirm

"history文件需要记录的行数
set history=100

"启动时不显示提示
set shortmess=atl

"不闪烁
set novisualbell

set foldenable
set fdls=1
"设置语法折叠
set foldmethod=syntax
"设置折叠区域宽度
set foldcolumn=3
"用空格来开关折叠
nnoremap <space> @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>
autocmd FileType php map <F9> <ESC>@=((foldclosed(line('.')) < 0) ? 'zM' : 'zR')<CR>

set nofoldenable

set sm "显示括号配对情况

"Auto Complete opt
"set completeopt=longest,menuone

"turn on omnicompletion
set ofu=syntaxcomplete#Complete

"Auto-completion of functions and constants
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#complete

set complete-=k complete+=k

"tab
imap <silent> <F3> <ESC>:tabnew<CR><F7>
map <silent> <F3> :tabnew<CR><F7>
imap <silent> <F4> <ESC>:tabclose<CR>
map <silent> <F4> :tabclose<CR>
imap <silent> gb <ESC>:tabprev<CR>
map <silent> gb :tabprev<CR>

"File history
let MRU_Max_Entries=20

"Search
set noignorecase

"Switch buffer
"Switch in different parts
map <silent> <LEADER>q :q<CR>
map <silent> <LEADER><LEADER> :w<CR>
map <silent> <LEADER>h :sp<CR>
map <silent> <LEADER>v :vsp<CR>
map <silent> <LEADER>a <C-W><Left>
map <silent> <LEADER>f <C-W><Right>
map <silent> <LEADER>s <C-W><Down>
map <silent> <LEADER>d <C-W><Up>
map <silent> <LEADER>= <C-W>+
map <silent> <LEADER>- <C-W>-
map <silent> <LEADER>z <C-W>_

"c/v key mapping
vmap <C-c> "+y
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <C-r><C-o>+
nmap <C-v> "+p

"------------------------- Vundle Start ------------------------------"

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/*

call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'

Plugin 'tpope/vim-fugitive'

Plugin 'vim-scripts/AutoComplPop'
Plugin 'ervandew/supertab'

" snipmate
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'

Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-markdown'

Plugin 'tomasr/molokai'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

"------------------------- Vundle End ------------------------------"


"NERD Tree
let NERDTreeChDirMode=2
au VimEnter * NERDTree "auto open
map <silent> <F3> :NERDTreeToggle<CR>
imap <silent> <F3> <ESC>:NERDTreeToggle<CR>

"ACP - with Super Tab
let g:acp_mappingDriven = 0 
let g:acp_completeoptPreview=0
let g:acp_completeOption = '.,w,b,t,i,d,k,u,U,s'
let g:acp_completeOption = '.,w,b,u,t,i,k'
let g:acp_behaviorPhpOmniLength = 1
let g:acp_behaviorKeywordLength = 1
autocmd FileType php let g:acp_behaviorKeywordLength = 2

"molokai
colorscheme molokai


